name: Build EXE

on:
  push:
    branches:
      - main  # או כל ענף אחר שתרצה

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # גרסת Python שלך

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install bs4
          pip install gematriapy
          pip install base64
          pip install urllib3
          pip install PyQt5-Qt5
          pip install PyQt5
          pip install pyluach

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --windowed --clean --onefile AAA.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe-file
          path: dist/AAA.exe
